version: '3.9'
services:
  db:
    image: mysql:5.7
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "senha123"
      MYSQL_DATABASE: "webdb"
    volumes:
    - ./data/mysql:/var/lib/mysql
    networks:
      -webnet
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
    - '4500:80'
    volumes:
    - ./data/php:/app
    networks:
      -webnet
